with open('user/views.py', 'rb') as f:
    content = f.read()

# Normalize line endings
content = content.replace(b'\r\n', b'\n')

# Fix the entire UsuarioDeleteView class
old = b'class UsuarioDeleteView(UsuarioPermissionMixin, DeleteView):\n    model = User\n    template_name = \'usuarios/confirm_delete.html\'\n    success_url = reverse_lazy(\'semeq:cadastro_usuarios\')\n    \n    def get_queryset(self):\n        perfil = self.request.user.perfil if hasattr(self.request.user, \'perfil\') else None\n        \n        qs = User.objects.select_related(\'perfil\', \'perfil__equipe\')\n        \n        # Admin/Gestor: veem todos os usu\xc3\xa1rios EXCETO eles mesmos\n        if perfil and perfil.is_gestor_or_above():\n            return qs.exclude(pk=self.request.user.pk).order_by(\'first_name\', \'last_name\', \'username\')\n        \n        # L\xc3\xadder/Colaborador: veem apenas seu pr\xc3\xb3prio registro\n        return qs.filter(pk=self.request.user.pk)\n    \n    def get_object(self, queryset=None):\n        obj = super().get_object(queryset)\n        # Impede auto-exclus\xc3\xa3o\n        if obj == self.request.user:\n            messages.error(self.request, \'Voc\xc3\xaa n\xc3\xa3o pode excluir seu pr\xc3\xb3prio usu\xc3\xa1rio.\')\n            raise PermissionDenied\n        return obj\n    \ndef get_context_data(self, **kwargs):\n        context = super().get_context_data(**kwargs)\n        # Count related apontamentos\n        from user.models import Apontamento\n        user = self.object\n        context[\"apontamentos_count\"] = Apontamento.objects.filter(responsavel=user).count()\n        # Check if current user is admin or gestor\n        perfil = self.request.user.perfil if hasattr(self.request.user, \"perfil\") else None\n        context[\"is_admin\"] = self.request.user.is_superuser or (perfil and perfil.is_admin())\n        context[\"is_admin_or_gestor\"] = self.request.user.is_superuser or (perfil and perfil.is_gestor_or_above())\n        context[\"show_delete_apontamentos_checkbox\"] = context[\"is_admin_or_gestor\"] and context[\"apontamentos_count\"] > 0\n        return context\n    \n    '

new = b'class UsuarioDeleteView(UsuarioPermissionMixin, DeleteView):\n    model = User\n    template_name = \'usuarios/confirm_delete.html\'\n    success_url = reverse_lazy(\'semeq:cadastro_usuarios\')\n    \n    def get_queryset(self):\n        perfil = self.request.user.perfil if hasattr(self.request.user, \'perfil\') else None\n        \n        qs = User.objects.select_related(\'perfil\', \'perfil__equipe\')\n        \n        # Admin/Gestor: veem todos os usu\xc3\xa1rios EXCETO eles mesmos\n        if perfil and perfil.is_gestor_or_above():\n            return qs.exclude(pk=self.request.user.pk).order_by(\'first_name\', \'last_name\', \'username\')\n        \n        # L\xc3\xadder/Colaborador: veem apenas seu pr\xc3\xb3prio registro\n        return qs.filter(pk=self.request.user.pk)\n    \n    def get_object(self, queryset=None):\n        obj = super().get_object(queryset)\n        # Impede auto-exclus\xc3\xa3o\n        if obj == self.request.user:\n            messages.error(self.request, \'Voc\xc3\xaa n\xc3\xa3o pode excluir seu pr\xc3\xb3prio usu\xc3\xa1rio.\')\n            raise PermissionDenied\n        return obj\n    \n    def get_context_data(self, **kwargs):\n        context = super().get_context_data(**kwargs)\n        # Count related apontamentos\n        from user.models import Apontamento\n        user = self.object\n        context[\"apontamentos_count\"] = Apontamento.objects.filter(responsavel=user).count()\n        # Check if current user is admin or gestor\n        perfil = self.request.user.perfil if hasattr(self.request.user, \"perfil\") else None\n        context[\"is_admin\"] = self.request.user.is_superuser or (perfil and perfil.is_admin())\n        context[\"is_admin_or_gestor\"] = self.request.user.is_superuser or (perfil and perfil.is_gestor_or_above())\n        context[\"show_delete_apontamentos_checkbox\"] = context[\"is_admin_or_gestor\"] and context[\"apontamentos_count\"] > 0\n        return context\n    \n    '

if old in content:
    content = content.replace(old, new)
    print('Replaced')
else:
    print('Not found')

with open('user/views.py', 'wb') as f:
    f.write(content)
print('Done')