# Generated by Django 6.0.7 on 2026-08-10 13:24

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome completo')),
                ('description', models.CharField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Descrição')),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('create_at', models.DateField(verbose_name='Data criada')),
                ('updated_at', models.DateField(verbose_name='Última alteração')),
            ],
        ),
    ]
