# Generated by Django 6.0.7 on 2026-08-10 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True, verbose_name='Nome')),
                ('description', models.CharField(unique=True, verbose_name='Descrição')),
                ('create_at', models.DateField(verbose_name='Data criada')),
                ('updated_at', models.DateField(verbose_name='Última alteração')),
            ],
        ),
    ]
