# Generated by Django 6.1 on 2026-08-06 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_id', models.CharField(max_length=50, verbose_name='ID Corporação')),
                ('corporation', models.CharField(max_length=200, verbose_name='Corporação')),
                ('plant_id', models.CharField(max_length=50, verbose_name='ID Planta')),
                ('plant', models.CharField(max_length=200, verbose_name='Planta')),
                ('unat', models.CharField(blank=True, max_length=200, verbose_name='UNAT')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state_province', models.CharField(blank=True, max_length=50, verbose_name='Estado/Província')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('iso_3166', models.CharField(blank=True, max_length=10, verbose_name='ISO 3166')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Região')),
                ('business', models.CharField(blank=True, max_length=200, verbose_name='Negócio')),
                ('sap_bp_code', models.CharField(blank=True, max_length=50, verbose_name='Código SAP BP')),
                ('zone', models.CharField(blank=True, max_length=50, verbose_name='Zona')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['corporation', 'plant'],
                'indexes': [models.Index(fields=['corporation_id'], name='user_client_corpora_4c1700_idx'), models.Index(fields=['plant_id'], name='user_client_plant_i_03fcba_idx'), models.Index(fields=['corporation'], name='user_client_corpora_f2bd9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gateway', 'Gateway'), ('bomba', 'Bomba'), ('sensor', 'Sensor'), ('controlador', 'Controlador'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Nº Série')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='user.cliente')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['cliente', 'tipo', 'numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('lider', 'Líder'), ('tecnico', 'Técnico')], default='tecnico', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
