# Generated by Django 6.0.7 on 2026-08-10 13:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Senha')),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('last_login', models.DateField(verbose_name='Último Login')),
                ('create_at', models.DateField(verbose_name='Data criada')),
                ('updated_at', models.DateField(verbose_name='Última alteração')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.team', verbose_name='team_id')),
            ],
        ),
    ]
