# Generated by Django 6.1 on 2026-08-06 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Time')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.time', verbose_name='Time/Equipe'),
        ),
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=200, verbose_name='Projeto')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('ticket', models.CharField(max_length=100, verbose_name='Ticket')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade')),
                ('equipe', models.CharField(choices=[('pmc', 'PMC'), ('shd', 'SHD'), ('campo', 'Campo')], max_length=10, verbose_name='Equipe')),
                ('atividade', models.CharField(choices=[('suporte', 'Suporte'), ('instalacao', 'Instalação'), ('treinamento', 'Treinamento'), ('manutencao', 'Manutenção')], max_length=20, verbose_name='Atividade')),
                ('tipo_problema', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('comunicacao', 'Comunicação'), ('configuracao', 'Configuração')], max_length=20, verbose_name='Tipo do Problema')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('homologacao', 'Homologação'), ('cancelado', 'Cancelado')], default='aberto', max_length=15, verbose_name='Status')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicial', models.TimeField(verbose_name='Hora Inicial')),
                ('hora_final', models.TimeField(verbose_name='Hora Final')),
                ('tempo_total', models.DurationField(blank=True, null=True, verbose_name='Tempo Total')),
                ('gw_ar', models.BooleanField(default=False, verbose_name='GW no Ar')),
                ('atend_after_18', models.BooleanField(default=False, verbose_name='Atendimento após 18h')),
                ('desvio', models.CharField(choices=[('nenhum', 'Nenhum'), ('cliente', 'Cliente'), ('infraestrutura', 'Infraestrutura')], default='nenhum', max_length=20, verbose_name='Desvio')),
                ('descricao', models.TextField(verbose_name='Descrição do Atendimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos', to='user.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos', to='user.equipamento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apontamento',
                'verbose_name_plural': 'Apontamentos',
                'ordering': ['-data', '-hora_inicial'],
                'indexes': [models.Index(fields=['data'], name='user_aponta_data_20bf5d_idx'), models.Index(fields=['status'], name='user_aponta_status_675115_idx'), models.Index(fields=['responsavel'], name='user_aponta_respons_12d051_idx'), models.Index(fields=['cliente'], name='user_aponta_cliente_9e7976_idx')],
            },
        ),
    ]
