# Generated by Django 6.1 on 2026-08-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_time_perfilusuario_time_apontamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='iso_3166',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sap_bp_code',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('lider', 'Líder'), ('usuario', 'Usuário')], default='usuario', max_length=20),
        ),
    ]
