# Generated by Django 6.1 on 2026-08-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_cliente_iso_3166_remove_cliente_sap_bp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apontamento',
            name='atend_after_18',
        ),
        migrations.AddField(
            model_name='apontamento',
            name='horario_atendimento',
            field=models.CharField(choices=[('normal', 'Normal (08:00-18:00)'), ('apos_18h', 'Após 18h (18:01-23:59)'), ('antes_8h', 'Antes 8h (00:01-08:00)'), ('madrugada', 'Madrugada (00:01-08:00)')], default='normal', max_length=20, verbose_name='Horário do Atendimento'),
        ),
    ]
