# Generated by Django 6.1 on 2026-08-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_apontamento_atend_after_18_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última alteração de senha'),
        ),
    ]
