# Generated by Django 6.1 on 2026-08-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_perfilusuario_last_password_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apontamento',
            name='horario_atendimento',
        ),
    ]
