# Generated by Django 6.1 on 2026-08-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_horario_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamento',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em execução'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=15, verbose_name='Status'),
        ),
    ]
