# Generated by Django 6.1 on 2026-08-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_apontamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tema_preferido',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Tema Preferido'),
        ),
    ]
