# Generated by Django 6.1 on 2026-08-10 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_perfilusuario_tema_preferido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apontamento',
            constraint=models.UniqueConstraint(fields=('responsavel', 'data', 'hora_inicial'), name='uniq_apontamento_resp_data_hora_inicial'),
        ),
    ]
