# Generated by Django 6.1 on 2026-08-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_apontamento_uniq_apontamento_resp_data_hora_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamento',
            name='equipe',
            field=models.CharField(choices=[('pmc', 'PMC'), ('shd', 'SHD')], max_length=10, verbose_name='Equipe'),
        ),
    ]
