# Generated by Django 6.1 on 2026-08-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_apontamento_equipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apontamento',
            name='uniq_apontamento_resp_data_hora_inicial',
        ),
    ]
