# Generated by Django 6.1 on 2026-08-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_apontamento_uniq_apontamento_resp_data_hora_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamento',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Apontamento'),
        ),
    ]
