# Generated by Django 6.1 on 2026-08-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_apontamento_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="apontamento",
            name="apos_18h",
            field=models.BooleanField(default=False, verbose_name="Trabalho após 18h"),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="tempo_minutos",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tempo (minutos)"
            ),
        ),
    ]
