# Generated by Django 6.1 on 2026-08-18 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_apontamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='equipamento_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Equipamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='user.cliente'),
        ),
    ]
