# Generated by Django 6.1 on 2026-08-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_apontamento_apos_18h_apontamento_tempo_minutos'),
        ('user', '0013_equipamento_equipamento_id_alter_equipamento_cliente'),
    ]

    operations = [
    ]
