# Generated by Django 6.1 on 2026-08-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_merge_20260821_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='business',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='country',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='region',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='unat',
        ),
    ]
