# Generated by Django 6.1 on 2026-08-26 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_merge_20260821_1731"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="email_verificado",
            field=models.BooleanField(default=False, verbose_name="Email verificado"),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="email_verificado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Email verificado em"
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("expira_em", models.DateTimeField()),
                ("usado", models.BooleanField(default=False)),
                ("usado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Verificação de Email",
                "verbose_name_plural": "Tokens de Verificação de Email",
            },
        ),
    ]
