# Generated by Django 6.1 on 2026-08-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_cliente_ativo_remove_cliente_business_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['tipo', 'modelo'], 'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='numero_serie',
        ),
    ]
