# Generated by Django 6.1 on 2026-08-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_equipamento_options_remove_equipamento_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='equipamento_id',
        ),
    ]
