# Generated by Django 6.1 on 2026-08-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_equipamento_equipamento_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='user_client_corpora_4c1700_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='user_client_plant_i_03fcba_idx',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='corporation_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='plant_id',
        ),
    ]
