# Generated by Django 6.1 on 2026-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_cliente_user_client_corpora_4c1700_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'Status',
                'ordering': ['status'],
            },
        ),
    ]
