# Generated by Django 6.1 on 2026-08-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_perfilusuario_email_verificado_and_more"),
        ("user", "0019_status"),
    ]

    operations = []
