# Generated by Django 6.1 on 2026-08-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_merge_20260827_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="apontamento",
            name="tempo_atendimento_minutos",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tempo de Atendimento (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="tempo_fim_atendimento",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Fim do Atendimento"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="tempo_inicio_atendimento",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Início do Atendimento"
            ),
        ),
    ]
