# Generated by Django 6.1 on 2026-08-27 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_apontamento_tempo_atendimento_minutos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoProblema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Tipo de Problema"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Problema",
                "verbose_name_plural": "Tipos de Problema",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="tipo_problema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.tipoproblema",
                verbose_name="Tipo do Problema",
            ),
        ),
    ]
