# Generated by Django 6.1 on 2026-08-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_tipoproblema_alter_apontamento_tipo_problema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apontamento",
            name="ticket",
            field=models.CharField(
                blank=True, max_length=100, unique=True, verbose_name="Ticket"
            ),
        ),
    ]
