# Generated by Django 6.1 on 2026-08-28 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_alter_apontamento_ticket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Atividade"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Equipe"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Equipe",
                "verbose_name_plural": "Equipes",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Prioridade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Prioridade"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Prioridade",
                "verbose_name_plural": "Prioridades",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ["ordem", "status"],
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
            },
        ),
        migrations.RemoveIndex(
            model_name="cliente",
            name="user_client_corpora_f2bd9a_idx",
        ),
        migrations.RenameIndex(
            model_name="apontamento",
            new_name="user_aponta_status__afccd5_idx",
            old_name="user_aponta_status_675115_idx",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="tempo_minutos",
        ),
        migrations.AddField(
            model_name="status",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="status",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="ordem",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordem de Exibição"
            ),
        ),
        migrations.AddField(
            model_name="tipoproblema",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tipoproblema",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tipoproblema",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apontamentos",
                to="user.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apontamentos_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="descricao",
            field=models.TextField(verbose_name="Descrição do Atendimento"),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="equipamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apontamentos",
                to="user.equipamento",
                verbose_name="Equipamento",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apontamentos_responsavel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.status",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="last_password_change",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última troca de senha"
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("gestor", "Gestor"),
                    ("lider", "Líder"),
                    ("usuario", "Usuário"),
                ],
                default="usuario",
                max_length=20,
                verbose_name="Função",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="tema_preferido",
            field=models.CharField(
                default="light", max_length=20, verbose_name="Tema preferido"
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(max_length=200, unique=True, verbose_name="Status"),
        ),
        migrations.AlterField(
            model_name="tipoproblema",
            name="nome",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Tipo de Problema"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together={("corporation", "plant", "zone")},
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="atividade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.atividade",
                verbose_name="Atividade",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="equipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.equipe",
                verbose_name="Equipe",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="prioridade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.prioridade",
                verbose_name="Prioridade",
            ),
        ),
        migrations.AddConstraint(
            model_name="apontamento",
            constraint=models.UniqueConstraint(
                fields=("responsavel", "data", "hora_inicial", "hora_final"),
                name="uniq_apontamento_resp_data_hora",
            ),
        ),
    ]
