# Generated by Django 6.1 on 2026-08-28 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_atividade_equipe_prioridade_alter_status_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfilusuario",
            name="time",
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="equipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.equipe",
                verbose_name="Equipe",
            ),
        ),
    ]
