# Generated by Django 6.1 on 2026-08-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_remove_perfilusuario_time_perfilusuario_equipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apontamento",
            name="apos_18h",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="desvio",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="gw_ar",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="tempo_atendimento_minutos",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="tempo_fim_atendimento",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="tempo_inicio_atendimento",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="ticket",
        ),
    ]
