# Generated by Django 6.1 on 2026-08-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0026_remove_apontamento_apos_18h_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apontamento",
            name="numero_sequencial",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Número Sequencial"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="tempo_atendimento_minutos",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tempo de Atendimento (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="tempo_fim_atendimento",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Fim do Atendimento"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="tempo_inicio_atendimento",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Início do Atendimento"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="ticket",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Ticket",
            ),
        ),
    ]
