# Generated by Django 6.1 on 2026-08-29 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_apontamento_numero_sequencial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Projeto"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Solicitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Solicitante"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Solicitante",
                "verbose_name_plural": "Solicitantes",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.projeto",
                verbose_name="Projeto",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="solicitante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.solicitante",
                verbose_name="Solicitante",
            ),
        ),
    ]
