# Generated by Django 6.1 on 2026-08-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_projeto_solicitante_alter_apontamento_projeto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamento",
            name="device",
            field=models.CharField(blank=True, max_length=100, verbose_name="Device"),
        ),
    ]
