# Generated by Django 6.1 on 2026-09-02 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_equipamento_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApontamentoTempo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("hora_inicial", models.TimeField(verbose_name="Hora Inicial")),
                ("hora_final", models.TimeField(verbose_name="Hora Final")),
                (
                    "tempo_total",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Tempo Total"
                    ),
                ),
                (
                    "tempo_total_minutos",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tempo Total (minutos)"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Apontamento de Tempo",
                "verbose_name_plural": "Apontamentos de Tempo",
                "ordering": ["-data", "-hora_inicial"],
            },
        ),
        migrations.CreateModel(
            name="Atendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_sequencial",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Número Sequencial",
                    ),
                ),
                (
                    "ticket",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Ticket",
                    ),
                ),
                (
                    "data_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Inicial"
                    ),
                ),
                (
                    "data_final",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Final/Prazo"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(verbose_name="Descrição do Atendimento"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Atendimento",
                "verbose_name_plural": "Atendimentos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="tipo",
            field=models.CharField(max_length=100, verbose_name="Tipo"),
        ),
        migrations.AddIndex(
            model_name="atividade",
            index=models.Index(
                fields=["ativo", "ordem"], name="atividade_ativo_ordem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atividade",
            index=models.Index(fields=["nome"], name="atividade_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(fields=["expira_em"], name="emailtoken_expira_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(
                fields=["usado", "expira_em"], name="emailtoken_usado_expira_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipe",
            index=models.Index(
                fields=["ativo", "ordem"], name="equipe_ativo_ordem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipe",
            index=models.Index(fields=["nome"], name="equipe_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="prioridade",
            index=models.Index(
                fields=["ativo", "ordem"], name="prioridade_ativo_ordem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prioridade",
            index=models.Index(fields=["nome"], name="prioridade_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="projeto",
            index=models.Index(
                fields=["ativo", "ordem"], name="projeto_ativo_ordem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projeto",
            index=models.Index(fields=["nome"], name="projeto_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitante",
            index=models.Index(
                fields=["ativo", "ordem"], name="solicitante_ativo_ordem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solicitante",
            index=models.Index(fields=["nome"], name="solicitante_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(
                fields=["ativo", "ordem"], name="status_ativo_ordem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(fields=["status"], name="status_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="tipoproblema",
            index=models.Index(
                fields=["ativo", "ordem"], name="tipoproblema_ativo_ordem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tipoproblema",
            index=models.Index(fields=["nome"], name="tipoproblema_nome_idx"),
        ),
        migrations.AddField(
            model_name="apontamentotempo",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apontamentos_tempo_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="apontamentotempo",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apontamentos_tempo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="atividade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.atividade",
                verbose_name="Atividade",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atendimentos",
                to="user.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atendimentos_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="equipamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atendimentos",
                to="user.equipamento",
                verbose_name="Equipamento",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="equipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.equipe",
                verbose_name="Equipe",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="prioridade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.prioridade",
                verbose_name="Prioridade",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.projeto",
                verbose_name="Projeto",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atendimentos_responsavel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="solicitante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.solicitante",
                verbose_name="Solicitante",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.status",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="tipo_problema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.tipoproblema",
                verbose_name="Tipo do Problema",
            ),
        ),
        migrations.AddField(
            model_name="apontamentotempo",
            name="apontamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apontamentos_tempo",
                to="user.atendimento",
                verbose_name="Atendimento",
            ),
        ),
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["data_inicial"], name="user_atendi_data_in_8b9c72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["status"], name="user_atendi_status__c709b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["responsavel"], name="user_atendi_respons_d40007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["cliente"], name="user_atendi_cliente_60d64e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["equipe"], name="user_atendi_equipe__a1f11a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apontamentotempo",
            index=models.Index(
                fields=["apontamento", "data"], name="user_aponta_atendim_00608e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apontamentotempo",
            index=models.Index(
                fields=["responsavel", "data"], name="user_aponta_respons_435208_idx"
            ),
        ),
    ]
