# Generated by Django 6.1 on 2026-09-02 22:42

from django.db import migrations
from datetime import timedelta


def migrar_apontamentos_para_atendimento(apps, schema_editor):
    """
    Converte cada Apontamento existente em um Atendimento + um ApontamentoTempo.
    """
    Apontamento = apps.get_model('user', 'Apontamento')
    Atendimento = apps.get_model('user', 'Atendimento')
    ApontamentoTempo = apps.get_model('user', 'ApontamentoTempo')
    
    for ap in Apontamento.objects.all():
        # Criar Atendimento
        atendimento = Atendimento.objects.create(
            numero_sequencial=ap.numero_sequencial,
            ticket=ap.ticket,
            projeto=ap.projeto,
            solicitante=ap.solicitante,
            prioridade=ap.prioridade,
            equipe=ap.equipe,
            atividade=ap.atividade,
            tipo_problema=ap.tipo_problema,
            status=ap.status,
            data_inicial=ap.data,
            data_final=ap.data,
            descricao=ap.descricao,
            cliente=ap.cliente,
            equipamento=ap.equipamento,
            responsavel=ap.responsavel,
            criado_por=ap.criado_por,
            criado_em=ap.criado_em,
            atualizado_em=ap.atualizado_em,
        )
        
        # Criar ApontamentoTempo (o primeiro/único apontamento)
        ApontamentoTempo.objects.create(
            atendimento=atendimento,
            data=ap.data,
            hora_inicial=ap.hora_inicial,
            hora_final=ap.hora_final,
            tempo_total=ap.tempo_total,
            tempo_total_minutos=ap.tempo_minutos,
            observacao="Apontamento migrado automaticamente",
            responsavel=ap.responsavel,
            criado_por=ap.criado_por,
            criado_em=ap.criado_em,
            atualizado_em=ap.atualizado_em,
        )


def reverter_migracao(apps, schema_editor):
    """
    Reverte a migração - apaga os Atendimentos e ApontamentosTempo criados.
    """
    Atendimento = apps.get_model('user', 'Atendimento')
    ApontamentoTempo = apps.get_model('user', 'ApontamentoTempo')
    
    ApontamentoTempo.objects.all().delete()
    Atendimento.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0030_create_atendimento_apontamentotempo"),
    ]

    operations = [
        migrations.RunPython(
            migrar_apontamentos_para_atendimento,
            reverse_code=reverter_migracao,
        ),
    ]