# Generated by Django 6.1 on 2026-09-03 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0031_migrate_apontamento_to_atendimento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="apontamentotempo",
            constraint=models.UniqueConstraint(
                fields=("apontamento", "data"),
                name="uniq_apontamentotempo_atendimento_data",
            ),
        ),
    ]
