# Generated by Django 6.1 on 2026-09-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_add_unique_constraint_apontamentotempo"),
    ]

    operations = [
        migrations.AddField(
            model_name="apontamentotempo",
            name="tempo_investido_minutos",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tempo realmente trabalhado (opcional - se preenchido, sobrescreve o tempo calculado de hora_inicial até hora_final)",
                null=True,
                verbose_name="Tempo Investido (minutos)",
            ),
        ),
        migrations.AlterField(
            model_name="apontamentotempo",
            name="tempo_total",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Tempo Total (calculado)"
            ),
        ),
        migrations.AlterField(
            model_name="apontamentotempo",
            name="tempo_total_minutos",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tempo Total Calculado (minutos)"
            ),
        ),
    ]
