# Generated by Django 6.1 on 2026-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0033_add_tempo_investido_minutos"),
    ]

    operations = [
        migrations.AddField(
            model_name="apontamento",
            name="tempo_investido_minutos",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tempo realmente trabalhado em minutos. Se preenchido, sobrescreve o tempo calculado de Hora Inicial até Hora Final.",
                null=True,
                verbose_name="Tempo Investido (minutos)",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="data_final",
            field=models.DateField(blank=True, null=True, verbose_name="Data Final"),
        ),
    ]
