# Generated by Django 6.1 on 2026-09-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0034_apontamento_tempo_investido_minutos_and_more"),
    ]

    operations = [
        # First-run fix: a coluna foi criada em 0034 (era AlterField lá).
        # Aqui vira AlterField para manter o estado final. DBs migrados: sem efeito.
        migrations.AlterField(
            model_name="apontamento",
            name="tempo_investido_minutos",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tempo realmente trabalhado em minutos. Se preenchido, será somado ao total dos apontamentos.",
                null=True,
                verbose_name="Tempo Investido (minutos)",
            ),
        ),
    ]
