# Generated by Django 6.1 on 2026-09-03 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0035_atendimento_tempo_investido_minutos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apontamento",
            options={
                "ordering": ["-data", "-data_final"],
                "verbose_name": "Apontamento",
                "verbose_name_plural": "Apontamentos",
            },
        ),
        migrations.RemoveConstraint(
            model_name="apontamento",
            name="uniq_apontamento_resp_data_hora",
        ),
        migrations.AddField(
            model_name="apontamento",
            name="data_final",
            field=models.DateField(blank=True, null=True, verbose_name="Data Final"),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="tempo_investido_minutos",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Tempo realmente trabalhado em minutos. Ex: 120 para 2h.",
                verbose_name="Tempo Investido (minutos)",
            ),
        ),
        migrations.AddConstraint(
            model_name="apontamento",
            constraint=models.UniqueConstraint(
                fields=("responsavel", "data", "data_final"),
                name="uniq_apontamento_resp_data",
            ),
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="hora_final",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="hora_inicial",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="tempo_atendimento_minutos",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="tempo_fim_atendimento",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="tempo_inicio_atendimento",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="tempo_total",
        ),
    ]
