# Generated by Django 6.1 on 2026-09-04 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0036_alter_apontamento_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="corporation",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Corporação"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="plant",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Planta"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["corporation", "plant"], name="cliente_corp_plant_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="apontamentotempo",
            constraint=models.CheckConstraint(
                condition=models.Q(("hora_final__gt", models.F("hora_inicial"))),
                name="apontamentotempo_hora_final_gt_inicial",
            ),
        ),
        migrations.AddConstraint(
            model_name="apontamento",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("data_final__gte", models.F("data_inicial")),
                    ("data_inicial__isnull", True),
                    ("data_final__isnull", True),
                    _connector="OR",
                ),
                name="atendimento_data_final_gte_inicial",
            ),
        ),
    ]
