# Generated by Django 6.1 on 2026-09-07 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0037_alter_cliente_corporation_alter_cliente_plant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="apontamentotempo",
            name="apontamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apontamentos_tempo",
                to="user.apontamento",
                verbose_name="Apontamento",
            ),
        ),
        migrations.AlterModelOptions(
            name="apontamento",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Apontamento",
                "verbose_name_plural": "Apontamentos",
            },
        ),
        migrations.RemoveConstraint(
            model_name="apontamento",
            name="uniq_apontamento_resp_data",
        ),
        # REMOVIDO (first-run fix): a constraint atendimento_data_final_gte_inicial
        # saiu de 0037 e é criada abaixo, após o AddField data_inicial.
        migrations.RemoveConstraint(
            model_name="apontamentotempo",
            name="uniq_apontamentotempo_atendimento_data",
        ),
        migrations.RemoveIndex(
            model_name="apontamento",
            name="user_aponta_data_20bf5d_idx",
        ),
        migrations.RemoveIndex(
            model_name="apontamento",
            name="user_aponta_status__afccd5_idx",
        ),
        migrations.RemoveIndex(
            model_name="apontamento",
            name="user_aponta_respons_12d051_idx",
        ),
        migrations.RemoveIndex(
            model_name="apontamento",
            name="user_aponta_cliente_9e7976_idx",
        ),
        migrations.RemoveIndex(
            model_name="apontamento",
            name="user_atendi_equipe__a1f11a_idx",
        ),
        migrations.RenameIndex(
            model_name="apontamentotempo",
            new_name="user_aponta_apontam_1e6769_idx",
            old_name="user_aponta_atendim_00608e_idx",
        ),
        migrations.AddField(
            model_name="apontamento",
            name="data_inicial",
            field=models.DateField(blank=True, null=True, verbose_name="Data Inicial"),
        ),
        # First-run fix: constraint de 0037 NÃO recriada aqui — o modelo final
        # (models.py) não tem esse CheckConstraint, e a validação vive no form.
        # (makemigrations --check confirma zero drift). DBs migrados: sem efeito.
        migrations.AlterField(
            model_name="apontamento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apontamentos",
                to="user.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apontamentos_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="descricao",
            field=models.TextField(verbose_name="Descrição do Apontamento"),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="equipamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apontamentos",
                to="user.equipamento",
                verbose_name="Equipamento",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apontamentos_responsavel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="tempo_investido_minutos",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tempo Investido (minutos)"
            ),
        ),
        migrations.AddConstraint(
            model_name="apontamentotempo",
            constraint=models.UniqueConstraint(
                fields=("apontamento", "data"),
                name="uniq_apontamentotempo_apontamento_data",
            ),
        ),
        # First-run fix: DeleteModel ANTES do AlterModelTable — a tabela
        # user_atendimento (Atendimento, criada em 0030) ainda existe aqui e
        # o rename da tabela do Apontamento colidia ("already another table").
        # 0039 é noop, então nenhum dado depende da ordem. DBs migrados: sem efeito.
        migrations.DeleteModel(
            name="Atendimento",
        ),
        migrations.AlterModelTable(
            name="apontamento",
            table="user_atendimento",
        ),
        migrations.RemoveField(
            model_name="apontamento",
            name="data",
        ),
    ]
