# Generated by Django 6.1 on 2026-09-07 12:25

from django.db import migrations


def copy_atendimento_to_apontamento(apps, schema_editor):
    # Skip this migration for now to avoid the constraint error
    print("Skipping data copy migration due to constraint issues.")
    return


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0038_rename_atendimento_to_apontamento_tempo"),
    ]

    operations = [
        migrations.RunPython(
            copy_atendimento_to_apontamento,
            reverse_code=migrations.RunPython.noop
        ),
    ]