# Generated by Django 6.1 on 2026-09-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0039_copy_atendimento_to_apontamento"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE user_apontamentotempo RENAME COLUMN atendimento_id TO apontamento_id;",
            reverse_sql="ALTER TABLE user_apontamentotempo RENAME COLUMN apontamento_id TO atendimento_id;",
        ),
    ]
