# Generated by Django 6.1 on 2026-09-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0040_fix_apontamentotempo_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipamento",
            options={
                "ordering": ["nome"],
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.RemoveField(
            model_name="equipamento",
            name="device",
        ),
        migrations.RemoveField(
            model_name="equipamento",
            name="modelo",
        ),
        migrations.RemoveField(
            model_name="equipamento",
            name="tipo",
        ),
        migrations.AddField(
            model_name="equipamento",
            name="nome",
            field=models.CharField(
                default="Equipamento", max_length=100, verbose_name="Nome"
            ),
        ),
    ]
