# Generated by Django 6.1 on 2026-09-08
from django.db import migrations


def normalize_emails(apps, schema_editor):
    """Normalize all emails to lowercase and strip whitespace."""
    User = apps.get_model('auth', 'User')
    db_alias = schema_editor.connection.alias
    
    # Get all users with non-normalized emails
    users = User.objects.using(db_alias).exclude(email='').exclude(email__isnull=True)
    
    for user in users:
        normalized = user.email.strip().lower()
        if normalized != user.email:
            user.email = normalized
            user.save(using=db_alias, update_fields=['email'])


def remove_duplicate_emails(apps, schema_editor):
    """Remove duplicate emails, keeping the oldest user (by id)."""
    User = apps.get_model('auth', 'User')
    db_alias = schema_editor.connection.alias
    
    # Find duplicate emails
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT email, MIN(id) as keep_id
            FROM auth_user
            WHERE email IS NOT NULL AND email != ''
            GROUP BY email
            HAVING COUNT(*) > 1
        """)
        duplicates = cursor.fetchall()
        
        for email, keep_id in duplicates:
            # Delete all but the oldest
            cursor.execute("""
                DELETE FROM auth_user 
                WHERE email = %s AND id != %s
            """, [email, keep_id])


def add_unique_email_index(apps, schema_editor):
    """Add unique index on email column."""
    schema_editor.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS auth_user_email_unique 
        ON auth_user (email)
        WHERE email IS NOT NULL AND email != ''
    """)


def remove_unique_email_index(apps, schema_editor):
    """Remove unique index on email column."""
    schema_editor.execute("""
        DROP INDEX IF EXISTS auth_user_email_unique
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_apontamento_data'),
    ]

    operations = [
        migrations.RunPython(normalize_emails, migrations.RunPython.noop),
        migrations.RunPython(remove_duplicate_emails, migrations.RunPython.noop),
        migrations.RunPython(add_unique_email_index, remove_unique_email_index),
    ]