# Generated by Django 6.1 on 2026-09-08
from django.db import migrations


def rename_usuario_to_colaborador(apps, schema_editor):
    """Rename 'usuario' role to 'colaborador' in PerfilUsuario."""
    PerfilUsuario = apps.get_model('user', 'PerfilUsuario')
    db_alias = schema_editor.connection.alias
    
    PerfilUsuario.objects.using(db_alias).filter(role='usuario').update(role='colaborador')


def rename_colaborador_to_usuario(apps, schema_editor):
    """Reverse: rename 'colaborador' back to 'usuario'."""
    PerfilUsuario = apps.get_model('user', 'PerfilUsuario')
    db_alias = schema_editor.connection.alias
    
    PerfilUsuario.objects.using(db_alias).filter(role='colaborador').update(role='usuario')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_normalize_email_add_unique'),
    ]

    operations = [
        migrations.RunPython(rename_usuario_to_colaborador, rename_colaborador_to_usuario),
    ]