# Generated by Django 6.1 on 2026-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0044_rename_usuario_to_colaborador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("gestor", "Gestor"),
                    ("lider", "Líder"),
                    ("colaborador", "Colaborador"),
                ],
                default="colaborador",
                max_length=20,
                verbose_name="Função",
            ),
        ),
    ]
