# Generated by Django 6.1 on 2026-09-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0045_alter_perfilusuario_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apontamento",
            name="tempo_investido_minutos",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Tempo Investido (minutos)",
            ),
        ),
    ]
