# Generated by Django 6.1 on 2026-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0046_fix_tempo_investido_minutos_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="prioridade",
            name="cor",
            field=models.CharField(
                default="#6c757d", max_length=7, verbose_name="Cor (Hex)"
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="cor",
            field=models.CharField(
                default="#6c757d", max_length=7, verbose_name="Cor (Hex)"
            ),
        ),
    ]
