# Generated by Django 6.1 on 2026-09-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0047_add_color_to_status_prioridade"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="is_concluido",
            field=models.BooleanField(
                default=False, verbose_name="Status de Conclusão"
            ),
        ),
    ]
