# Generated by Django 6.1 on 2026-09-11 14:44

from django.db import migrations


def create_fixed_statuses(apps, schema_editor):
    Status = apps.get_model('user', 'Status')
    
    # Definir os 3 status fixos do sistema
    fixed_statuses = [
        {'status': 'Aberto', 'ordem': 10, 'cor': '#0d6efd', 'is_concluido': False},
        {'status': 'Executando', 'ordem': 20, 'cor': '#ffc107', 'is_concluido': False},
        {'status': 'Concluído', 'ordem': 30, 'cor': '#198754', 'is_concluido': True},
    ]
    
    for st in fixed_statuses:
        Status.objects.update_or_create(
            status=st['status'],
            defaults={
                'ordem': st['ordem'],
                'cor': st['cor'],
                'is_concluido': st['is_concluido'],
                'ativo': True,
            }
        )


def remove_fixed_statuses(apps, schema_editor):
    Status = apps.get_model('user', 'Status')
    Status.objects.filter(status__in=['Aberto', 'Executando', 'Concluído']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0048_add_is_concluido_to_status"),
    ]

    operations = [
        migrations.RunPython(create_fixed_statuses, remove_fixed_statuses),
    ]
