# Generated by Django 6.1 on 2026-09-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0049_populate_fixed_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apontamento",
            name="numero_sequencial",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Número Sequencial"
            ),
        ),
    ]
