# Generated by Django 6.1 on 2026-09-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0050_alter_apontamento_numero_sequencial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apontamento",
            new_name="user_aponta_data_in_77fcae_idx",
            old_name="user_atendi_data_in_8b9c72_idx",
        ),
        migrations.RenameIndex(
            model_name="apontamento",
            new_name="user_aponta_status__afccd5_idx",
            old_name="user_atendi_status__c709b5_idx",
        ),
        migrations.RenameIndex(
            model_name="apontamento",
            new_name="user_aponta_respons_12d051_idx",
            old_name="user_atendi_respons_d40007_idx",
        ),
        migrations.RenameIndex(
            model_name="apontamento",
            new_name="user_aponta_cliente_9e7976_idx",
            old_name="user_atendi_cliente_60d64e_idx",
        ),
        migrations.AlterModelTable(
            name="apontamento",
            table="user_apontamento",
        ),
    ]
