# Generated by Django 6.1 on 2026-09-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0050_alter_apontamento_numero_sequencial"),
    ]

    operations = [
        # First-run fix: os RenameIndex originais pressupunham índices
        # user_atendi_* criados em 0030, removidos por redundância/conflito
        # (estado final idêntico: os nomes user_aponta_* de status/responsavel/
        # cliente já existiam via 0002/0024 e foram removidos em 0038).
        # Aqui recriamos os 4 índices finais diretamente. DBs migrados: sem efeito.
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["data_inicial"], name="user_aponta_data_in_77fcae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["status"], name="user_aponta_status__afccd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["responsavel"], name="user_aponta_respons_12d051_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["cliente"], name="user_aponta_cliente_9e7976_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="apontamento",
            table="user_apontamento",
        ),
    ]
