# Generated by Django 6.1 on 2026-09-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user",
            "0051_rename_user_atendi_data_in_8b9c72_idx_user_aponta_data_in_77fcae_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="plant_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="ID da Planta"
            ),
        ),
    ]
