# Generated by Django 6.1 on 2026-09-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0052_add_plant_id_to_cliente"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipamento",
            options={
                "ordering": ["ordem", "nome"],
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="ordem",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordem de Exibição"
            ),
        ),
        migrations.AddIndex(
            model_name="equipamento",
            index=models.Index(
                fields=["ativo", "ordem"], name="equipamento_ativo_ordem_idx"
            ),
        ),
    ]
