# Generated by Django 6.1 on 2026-09-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0053_alter_equipamento_options_cliente_ativo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipamento",
            options={
                "ordering": ["tipo", "device", "modelo"],
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.RemoveIndex(
            model_name="equipamento",
            name="equipamento_ativo_ordem_idx",
        ),
        migrations.AddField(
            model_name="equipamento",
            name="device",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Device"
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="modelo",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Modelo"
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("gateway", "Gateway"),
                    ("bomba", "Bomba"),
                    ("sensor", "Sensor"),
                    ("controlador", "Controlador"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddIndex(
            model_name="equipamento",
            index=models.Index(
                fields=["tipo", "device"], name="equipamento_tipo_device_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="equipamento",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="equipamento",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="equipamento",
            name="ordem",
        ),
    ]
