# Generated by Django 6.1 on 2026-09-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0054_equipamento_tipo_device_modelo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apontamento",
            name="ticket",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="ID"
            ),
        ),
    ]
