# Generated by Django 6.1 on 2026-09-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0055_ticket_para_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="tipo",
            field=models.CharField(
                default="outro", max_length=100, verbose_name="Tipo"
            ),
        ),
    ]
